version: '3'
services:
  httpd:
    image: httpd:2.4.33-alpine
    environment:
        - TZ=Europe/Paris
        - http_proxy
        - https_proxy
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/local/apache2/htdocs/
